### ISSUE TITLE
CSDL

### ISSUE THREAD

**Issue by nmtan2001** [ndvinh98/CS406.L11-Final-Project#1]
Cho em hỏi là anh còn giữ CSDL của project này không ạ ? em đang gặp khó khăn trong phần crawl csdl về nên nếu có còn thì anh có thể share cho em được không ạ ?

**Comment by ndvinh98** [comment]
link này nhé e:
https://www.mediafire.com/file/e772khbdap17v4p/AAAPistol.zip/file

data e kiếm ở trang này nhé https://miai.vn/thu-vien-mi-ai/


Vào Th 3, 18 thg 7, 2023 vào lúc 13:30 nmtan2001 ***@***.***>
đã viết:

**Comment by nmtan2001** [comment]
Em cảm ơn anh nhiều lắm ạ !!!

**Comment by nmtan2001** [comment]
Cho em hỏi là data của PJ này anh có giữ không ạ ? Em issue nhầm project :( 
https://github.com/ndvinh98/CS114.K21-Machine-Learning/tree/master

**Comment by ndvinh98** [comment]
qua repo này nhé e https://github.com/dlphan/crawl-smartphone-reviews-on-tgdd/tree/master/data

**Comment by nmtan2001** [comment]
em cảm ơn ạ :)
